/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode.begin.app;

import leetcode.begin.list.LinkedList;

import static leetcode.begin.utilities.StringUtils.join;
import static leetcode.begin.utilities.StringUtils.split;
import static leetcode.begin.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
